version: '3'

services:
  bot:
    build:
      context: bot
      dockerfile: Dockerfile
    networks:
      - backend
      - frontend
    ports:
      - "5004:5004"  # Порт для взаимодействия с ботом
    volumes:
      - shared_data:/app/tracks_wav
    command: python bot/main.py


  model:
    build:
      context: moco
      dockerfile: Dockerfile
    networks:
      - backend
    ports:
      - "5002:5000"  # Порт для Flask-приложения
      - "5003:5001"  # Дополнительный порт, если необходимо
    volumes:
      - shared_data:/app/tracks_wav
    command: python /app/moco/app.py
    depends_on:
      - bot  # указываем зависимость от сервиса bot


networks:
  backend:
    driver: bridge
  frontend:
    driver: bridge


volumes:
  shared_data:
