version: '3'

services:
  bot:
    build:
      context: bot
      dockerfile: Dockerfile
    container_name: bot
    networks:
      - backend
      - frontend
    ports:
      - "5005:5005"  # Порт для взаимодействия с ботом
    volumes:
      - shared_data:/app/tracks_wav
    command: python main.py


  model:
    build:
      context: moco
      dockerfile: Dockerfile
    container_name: model
    networks:
      - backend
    ports:
      - "5000:5000"  # Порт для Flask-приложения
    volumes:
      - shared_data:/app/tracks_wav
    command: python app.py
    depends_on:
      - bot  # указываем зависимость от сервиса bot


networks:
  backend:
    driver: bridge
  frontend:
    driver: bridge


volumes:
  shared_data:
