version: '3'

services:
  bot:
    build:
      context: bot
      dockerfile: Dockerfile
    networks:
      - backend
      - frontend
    ports:
      - "5004:5004"
    volumes:
      - shared_data:/app/tracks_wav
    command: python /app/bot/main.py


  model:
    build:
      context: moco
      dockerfile: Dockerfile
    networks:
      - backend
    ports:
      - "ZZZZ:ZZZZ"
      - "WWWW:WWWW"
    volumes:
      - shared_data:/app/tracks_wav
    command: python /app/moco/app.py


networks:
  backend:
    driver: bridge
  frontend:
    driver: bridge


volumes:
  shared_data:
