version: '3'

services:
  bot:
    build:
      context: bot
      dockerfile: bot/Dockerfile
    # Добавьте любые другие настройки для вашего бота

  model:
    build:
      context: bot
      dockerfile: bot/Dockerfile
    # Добавьте любые другие настройки для вашей модели
