version: '3'

services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile_bot
    # Добавьте любые другие настройки для вашего бота

  model:
    build:
      context: .
      dockerfile: Dockerfile_model
    # Добавьте любые другие настройки для вашей модели
